export interface BookItem {
  id: string;
  title: string;
  authors: string;
  description: string;
  vocabScore: number;
  pageCount: number;
  isSimplified: boolean;
  coverColor: string;
  coverUrl?: string;
}

export const BOOK_ITEMS: BookItem[] = [
  {
    "id": "335",
    "title": "A Good Friend",
    "authors": "World Stories",
    "description": "An English Story  *  Yasin’s family moved from Iraq to England when he was just a young boy. Yasin did not want to leave his home in Samarra but his f...",
    "vocabScore": 7997,
    "pageCount": 6,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/335.jpg"
  },
  {
    "id": "281",
    "title": "A Lesson of Tit for Tat",
    "authors": "World Stories",
    "description": "A Somali Story  *  The camel and the fox were very good friends and very good thieves. One day, the two friends decided to cross the river so that the...",
    "vocabScore": 4938,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/281.jpg"
  },
  {
    "id": "329",
    "title": "A Story of Courage",
    "authors": "World Stories",
    "description": "A Gujarati Story  *  Harjit Singh sat on the bench by the carousel at the airport, waiting for his suitcase to arrive. He was tired and cold and wasn’...",
    "vocabScore": 11499,
    "pageCount": 10,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/329.jpg"
  },
  {
    "id": "239",
    "title": "Adam and the Dragon's Treasure",
    "authors": "World Stories",
    "description": "A Polish Story  *  Adam lived in a small village in the south of Poland near to the big city of Krakow. Adam’s favourite part of the day was dinner ti...",
    "vocabScore": 16525,
    "pageCount": 15,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/239.jpg"
  },
  {
    "id": "240",
    "title": "Adem's Baba Embarrassed Him",
    "authors": "World Stories",
    "description": "A Turkish Story  *  Somewhere below the clouds there is an island called the United Kingdom. In the south of this island there is a city called London...",
    "vocabScore": 11966,
    "pageCount": 10,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/240.jpg"
  },
  {
    "id": "322",
    "title": "Aharsi: The Bengal Tiger",
    "authors": "World Stories",
    "description": "A Bengali Story  *  Aharsi, the big Bengal tiger, was having a good think. It was winter and he was still getting used to the feeling of ice on the pa...",
    "vocabScore": 8530,
    "pageCount": 7,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/322.jpg"
  },
  {
    "id": "822",
    "title": "Alfredo",
    "authors": "World Stories",
    "description": "*  Ants don’t have ears or noses, and even though they have mouths, they cannot speak. Instead, they have two long feelers on their head called antenn...",
    "vocabScore": 5713,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/822.jpg"
  },
  {
    "id": "823",
    "title": "Ali Baba and the Forty Thieves",
    "authors": "World Stories",
    "description": "A tale from the Arabian Nights  *  Each evening Ali Baba went out to gather twigs and branches for his wife so that she had enough firewood to cook th...",
    "vocabScore": 12140,
    "pageCount": 11,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/823.jpg"
  },
  {
    "id": "451",
    "title": "Ali Thumb",
    "authors": "World Stories",
    "description": "A Turkish Story  *  Once upon a time, a couple had a baby boy whom they called Ali.  The baby came as a surprise to his parents, because when he was b...",
    "vocabScore": 7549,
    "pageCount": 6,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/451.jpg"
  },
  {
    "id": "375",
    "title": "Be Truthful",
    "authors": "World Stories",
    "description": "A Hindi Story  *  There once lived a small boy called Pukhraj who was the son of a farmer. The one trouble with Pukhraj was that he often told lies to...",
    "vocabScore": 5267,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/375.jpg"
  },
  {
    "id": "392",
    "title": "Beauty",
    "authors": "World Stories",
    "description": "A Gujarati Story  *  ‘I want a baby,’ Aadab demanded one day, ‘and I want a baby now. I'm young and beautiful, and I'm married. I need a baby before I...",
    "vocabScore": 7284,
    "pageCount": 6,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/392.jpg"
  },
  {
    "id": "832",
    "title": "Beauty and the Beast",
    "authors": "World Stories",
    "description": "Once upon a time, there was a struggling trader. He lived with his daughter, Beauty, in a small village in France. He left their home for a business t...",
    "vocabScore": 4730,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/832.jpg"
  },
  {
    "id": "1144",
    "title": "Beware the Dragon",
    "authors": "World Stories",
    "description": "*  Evening had fallen across the land. Sir Adi, Dame Sofia and Sir Thomas were suffering from empty stomachs and sore feet. The trio were brave knight...",
    "vocabScore": 10944,
    "pageCount": 9,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/1144.jpg"
  },
  {
    "id": "827",
    "title": "Bubbling with Happiness",
    "authors": "World Stories",
    "description": "*  One day, a wealthy man named Akito walked into an old curiosity shop in Japan. Akito was looking for a teapot in which he could make tea. He search...",
    "vocabScore": 5048,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/827.jpg"
  },
  {
    "id": "826",
    "title": "Carmen, The Farmer",
    "authors": "World Stories",
    "description": "*  Carmen was a ten-year-old girl who lived in a tiny village in the north of Spain.  Her parents had a farm with cows that made good milk. Sometimes...",
    "vocabScore": 2532,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/826.jpg"
  },
  {
    "id": "665",
    "title": "Chako Chaki",
    "authors": "World Stories",
    "description": "There was once a male sparrow and female sparrow who lived together happily. They jumped from one branch to another and flew freely. With team work, t...",
    "vocabScore": 2486,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/665.jpg"
  },
  {
    "id": "346",
    "title": "Chips",
    "authors": "World Stories",
    "description": "A Polish Story  *  Once upon a time, not so long ago, in a small house in a small village in the east of a big country, there lived a widow with lots...",
    "vocabScore": 8793,
    "pageCount": 7,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/346.jpg"
  },
  {
    "id": "877",
    "title": "Cinderella",
    "authors": "World Stories",
    "description": "A traditional French tale  *  Once upon a time there was a girl called Cinderella. She was called Cinderella because every morning and every night she...",
    "vocabScore": 6524,
    "pageCount": 5,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/877.jpg"
  },
  {
    "id": "666",
    "title": "City Mouse and Country Mouse",
    "authors": "World Stories",
    "description": "and  There once was a tiny little mouse from the city. One day, the city mouse went to visit his friend from the countryside; the country mouse.  The...",
    "vocabScore": 3049,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/666.jpg"
  },
  {
    "id": "667",
    "title": "Cormoran: The Cornish Giant",
    "authors": "World Stories",
    "description": "In Cornwall there is a small island, called St Michael’s Mount. You can only get there on foot at low tide. At high tide, you can only get there by bo...",
    "vocabScore": 5868,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/667.jpg"
  },
  {
    "id": "278",
    "title": "Crow and Little Bird",
    "authors": "World Stories",
    "description": "A Punjabi Story  *  One day, Little Bird invited Crow for dinner. Little Bird had spent the day preparing the meal and when it was ready she waited fo...",
    "vocabScore": 4110,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/278.jpg"
  },
  {
    "id": "242",
    "title": "Deer and Jaguar",
    "authors": "World Stories",
    "description": "A Brazilian Story  *  Deer walked along by the great river into the forest: ‘Oh, but what a life have I got? No home. Perhaps I will build myself a ho...",
    "vocabScore": 4845,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/242.jpg"
  },
  {
    "id": "244",
    "title": "Dick Whittington and his Cat",
    "authors": "World Stories",
    "description": "An English Story  *  A long time ago there was once a poor boy called Dick Whittington who had no mummy and daddy to look after him so he was often ve...",
    "vocabScore": 5838,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/244.jpg"
  },
  {
    "id": "354",
    "title": "Eight Royal Trees",
    "authors": "World Stories",
    "description": "A Bengali Story  *  There was once a powerful king who was married to seven queens. The king was a good ruler and a generous man, but he had no heir t...",
    "vocabScore": 4534,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/354.jpg"
  },
  {
    "id": "668",
    "title": "Friends Find a Way",
    "authors": "World Stories",
    "description": "In a dark, dense forest in New Zealand, there lived a little grub called Aaron.  He was white and small and moved by wiggling his body. Best of all, h...",
    "vocabScore": 4655,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/668.jpg"
  },
  {
    "id": "414",
    "title": "Friends Forever",
    "authors": "World Stories",
    "description": "An Akan Story from Ghana  *  There once lived a mouse and frog who were very good friends. Every morning the frog would go to visit the mouse who live...",
    "vocabScore": 3223,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/414.jpg"
  },
  {
    "id": "1037",
    "title": "Gingerbread Cookies",
    "authors": "World Stories",
    "description": "*  Back in medieval times, in a Polish town called Toruń, there lived a poor baker’s apprentice. His name was Bogumił.  Bogumił was not only honest an...",
    "vocabScore": 3903,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/1037.jpg"
  },
  {
    "id": "245",
    "title": "Goldilocks and the Three Bears",
    "authors": "World Stories",
    "description": "*  Once upon a time, in a little house on the edge of the woods, a girl called Goldilocks lived with her parents. One morning, she woke up as the sun...",
    "vocabScore": 5433,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/245.jpg"
  },
  {
    "id": "355",
    "title": "Half Rooster",
    "authors": "World Stories",
    "description": "An Albanian Story  *  Once upon a time, there was an old man and an old woman. All they had in the world was one cat and one rooster.  They were very...",
    "vocabScore": 6650,
    "pageCount": 5,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/355.jpg"
  },
  {
    "id": "345",
    "title": "Half a Year in Grã-Bretanha",
    "authors": "World Stories",
    "description": "A Story from Brazil and Britain  *  January  ‘Why does it always rain here?’ Natalia asked her mother.  Natalia’s mother looked up from her newspaper...",
    "vocabScore": 11551,
    "pageCount": 10,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/345.jpg"
  },
  {
    "id": "999",
    "title": "Hansel and Gretel",
    "authors": "World Stories",
    "description": "Once upon a time, there lived a poor woodcutter. He lived in a tiny village near a forest with his two children and his second wife. The children were...",
    "vocabScore": 5279,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/999.jpg"
  },
  {
    "id": "428",
    "title": "Hard Times (A True Story)",
    "authors": "World Stories",
    "description": "An Albanian Story  *  I was very young when the war started so I do not remember everything about it. I just remember that it was very scary, everybod...",
    "vocabScore": 4695,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/428.jpg"
  },
  {
    "id": "895",
    "title": "Harlequin's Mask",
    "authors": "World Stories",
    "description": "A tale about carnival’s most famous costume  *  Once upon a time, there was a child called Harlequin. He lived in Bergamo, a city in northern Italy....",
    "vocabScore": 3153,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/895.jpg"
  },
  {
    "id": "669",
    "title": "His Father's Kingdom",
    "authors": "World Stories",
    "description": "Once upon a time, a prince inherited his father’s kingdom. Although it had once been a prosperous nation of fertile lands, his father’s incompetence h...",
    "vocabScore": 3838,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/669.jpg"
  },
  {
    "id": "415",
    "title": "Home",
    "authors": "World Stories",
    "description": "A Tamil Story  *  It was a very hot day in May and Myna’s mother wouldn’t let her play out in the sun.  ‘I want to play with my friends!’ Myna protest...",
    "vocabScore": 11468,
    "pageCount": 10,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/415.jpg"
  },
  {
    "id": "670",
    "title": "How Arthur Became King",
    "authors": "World Stories",
    "description": "An English legend  Uther Pendragon stood with a group of his men on a high cliff watching the Roman ships.  One by one the huge wooden galleys set sai...",
    "vocabScore": 7361,
    "pageCount": 6,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/670.jpg"
  },
  {
    "id": "1467",
    "title": "How Life Is",
    "authors": "World Stories",
    "description": "A Spanish Story  *  Once, a poor old man lived in a small town. Everyone was jealous of him. Even the kings from miles around were jealous because he...",
    "vocabScore": 4167,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/1467.jpg"
  },
  {
    "id": "416",
    "title": "How the Old Woman Got Her Wish",
    "authors": "World Stories",
    "description": "A Story from India  *  A long time ago a blind old woman lived with her son and his wife in a small village in South India. They were very poor.  The...",
    "vocabScore": 3437,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/416.jpg"
  },
  {
    "id": "246",
    "title": "How the Tortoise Got his Crooked Shell",
    "authors": "World Stories",
    "description": "A Nigerian Story  *  A long time ago, a terrible famine hit an ancient animal kingdom. It had not rained for two whole years and all of the crops were...",
    "vocabScore": 8806,
    "pageCount": 7,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/246.jpg"
  },
  {
    "id": "671",
    "title": "Iris Mary and Grandad's Weather Sayings",
    "authors": "World Stories",
    "description": "and  The doorbell rang. Grandad was there.  Iris Mary ran to open the door. Iris Mary was just four years old.  It was raining, and Grandad was very w...",
    "vocabScore": 6092,
    "pageCount": 5,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/671.jpg"
  },
  {
    "id": "264",
    "title": "Jack and the Beanstalk",
    "authors": "World Stories",
    "description": "*  Once a poor widow had a son called Jack. She loved him dearly. They lived in a little house and all they owned was a cow called Daisy.  Sadly, the...",
    "vocabScore": 5040,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/264.jpg"
  },
  {
    "id": "238",
    "title": "Joha and his Donkey",
    "authors": "World Stories",
    "description": "A Saudi Arabian Story  *  One day, Joha was riding upon his donkey on the way to market. Joha’s son walked beside the donkey, holding the reins and ta...",
    "vocabScore": 3475,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/238.jpg"
  },
  {
    "id": "655",
    "title": "Juha Stories",
    "authors": "World Stories",
    "description": "One day, Juha bought ten donkeys. He rode on one of them and herded the nine in front of him. He started counting the donkeys and found only nine, for...",
    "vocabScore": 3783,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/655.jpg"
  },
  {
    "id": "453",
    "title": "Keloglan and the Magic Seal",
    "authors": "World Stories",
    "description": "A Turkish Story  *  One day, Keloğlan was walking back from the marketplace after selling his crops to the people of the neighbouring village. He had...",
    "vocabScore": 10044,
    "pageCount": 9,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/453.jpg"
  },
  {
    "id": "455",
    "title": "Keloglan and the Squirrel",
    "authors": "World Stories",
    "description": "A Turkish Story  *  Once upon a time, in a small village in Turkey, there lived a mother and her loyal son. Everyone knew the boy as Keloğlan, which m...",
    "vocabScore": 7501,
    "pageCount": 6,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/455.jpg"
  },
  {
    "id": "343",
    "title": "Kulumbu Yeye",
    "authors": "World Stories",
    "description": "A Nigerian Story  *  A long time ago, in the outskirts of Jago village, there lived a lioness and her cub, whose name was Kako. The lioness was very f...",
    "vocabScore": 7964,
    "pageCount": 6,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/343.jpg"
  },
  {
    "id": "417",
    "title": "Kweku Anansi and his New Wife",
    "authors": "World Stories",
    "description": "An Akan Story  *  One day, Kweku Anansi went to God to complain that his wife was nothing more than an extra mouth to feed. He also complained that sh...",
    "vocabScore": 4994,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/417.jpg"
  },
  {
    "id": "1145",
    "title": "Later!",
    "authors": "World Stories",
    "description": "*  Every day Oscar would do everything his way. Oscar would eat what he wanted, play the games he wanted whenever he liked and sleep whenever he wante...",
    "vocabScore": 8374,
    "pageCount": 7,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/1145.jpg"
  },
  {
    "id": "353",
    "title": "Li and Gao",
    "authors": "World Stories",
    "description": "A Chinese Story  *  Li was a foolish neighbour, but one day, in the gambling house, Li won three hundred yuan.  ‘Oh, what shall I do with my yuan? Whe...",
    "vocabScore": 1881,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/353.jpg"
  },
  {
    "id": "418",
    "title": "Lily and the Queen of Flowers",
    "authors": "World Stories",
    "description": "A Filipino Story  *  On a dull, grey day in May with the rain pouring down as usual, Lily walked through the park near her house. The dark clouds in t...",
    "vocabScore": 12946,
    "pageCount": 11,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/418.jpg"
  },
  {
    "id": "896",
    "title": "Long Hair",
    "authors": "World Stories",
    "description": "*  Long ago, there was a village at the foot of Mount Du, where the people of the Dong ethnicity lived. The area was suffering from drought. The local...",
    "vocabScore": 3674,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/896.jpg"
  },
  {
    "id": "1464",
    "title": "Master Twardowski",
    "authors": "World Stories",
    "description": "A Polish Story  *  Many centuries ago, a nobleman lived in Krakow. His name was Jan Twardowski. He was an educated man, and he loved books and science...",
    "vocabScore": 4215,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/1464.jpg"
  },
  {
    "id": "989",
    "title": "Medusa",
    "authors": "World Stories",
    "description": "A story from Ancient Greece  *  Many years ago, in a world almost forgotten, there lived a young girl named Medusa.  Medusa played in the hills and ra...",
    "vocabScore": 5206,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/989.jpg"
  },
  {
    "id": "275",
    "title": "Mistress Owl",
    "authors": "World Stories",
    "description": "A French Story  *  When Mistress Owl tentatively glanced out at the world from her cozy hollow in the tree trunk, she could tell by the winter sun tha...",
    "vocabScore": 5547,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/275.jpg"
  },
  {
    "id": "420",
    "title": "Not Alone",
    "authors": "World Stories",
    "description": "A Filipino Story  *  When Dalisay was just eight years old her mother told her that they would be leaving their home and moving to England.  ‘Your fat...",
    "vocabScore": 6628,
    "pageCount": 5,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/420.jpg"
  },
  {
    "id": "248",
    "title": "Pandora's Box",
    "authors": "World Stories",
    "description": "A Greek Story  *  Long ago and far away, high up amongst the clouds of Mount Olympus, the gods enjoyed a life of pleasure and quarrelling. Whenever th...",
    "vocabScore": 3526,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/248.jpg"
  },
  {
    "id": "1003",
    "title": "Peter of the Pigs",
    "authors": "World Stories",
    "description": "A traditional Portuguese story  *  Long ago, there was a boy called Peter. It was his job to look after some pigs. The boy was called Peter of the Pig...",
    "vocabScore": 2951,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/1003.jpg"
  },
  {
    "id": "1465",
    "title": "Puss in Boots",
    "authors": "World Stories",
    "description": "*  Once upon a time, there lived a miller who had three sons. When he died, he left the mill to his oldest son. He left the donkey to his middle son....",
    "vocabScore": 5546,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/1465.jpg"
  },
  {
    "id": "981",
    "title": "Robin Hood",
    "authors": "World Stories",
    "description": "A traditional English tale  Over seven hundred years ago there lived a young man called Robert of Locksley. His friends called him Robin.  Robin lived...",
    "vocabScore": 6663,
    "pageCount": 5,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/981.jpg"
  },
  {
    "id": "820",
    "title": "Romulus and Remus",
    "authors": "World Stories",
    "description": "A story from the traditional legends and myths of Ancient Rome, Italy  *  Once upon a time in a faraway land called Italy, the god Mars married Rhea S...",
    "vocabScore": 2909,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/820.jpg"
  },
  {
    "id": "163",
    "title": "Sleeping Beauty",
    "authors": "World Stories",
    "description": "A French Story  *  Long ago and far away there lived a good king and queen. The people loved them and their lives would have been very happy if only t...",
    "vocabScore": 7579,
    "pageCount": 6,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/163.jpg"
  },
  {
    "id": "421",
    "title": "Sow What",
    "authors": "World Stories",
    "description": "An English story set in France  *  It was the day after I came home with a bloody nose that Papi first took me to the allotment. I didn’t want to call...",
    "vocabScore": 13019,
    "pageCount": 12,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/421.jpg"
  },
  {
    "id": "627",
    "title": "Stone Soup",
    "authors": "World Stories",
    "description": "A long time ago, in a village not too far from a stream, a kind-hearted soldier was trudging down a dusty lane. His movements were slow as he had been...",
    "vocabScore": 5233,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/627.jpg"
  },
  {
    "id": "277",
    "title": "The Ant and the Elephant",
    "authors": "World Stories",
    "description": "An Afghan Story  *  Mahabis is a game played between two teams. One team places their hand beneath a blanket and hide a ring in the palm of a teammate...",
    "vocabScore": 2271,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/277.jpg"
  },
  {
    "id": "1466",
    "title": "The Baltic Sea Princess",
    "authors": "World Stories",
    "description": "*  Many years ago, at the bottom of the Baltic Sea, there lived a beautiful princess named Jurata. The walls and ceilings of her palace were made of a...",
    "vocabScore": 3549,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/1466.jpg"
  },
  {
    "id": "249",
    "title": "The Beauty of Difference",
    "authors": "World Stories",
    "description": "An Iranian Story  *  Shirin was still a relatively young girl when her parents sent her away from her home in Tehran to live in a big city in England...",
    "vocabScore": 11583,
    "pageCount": 10,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/249.jpg"
  },
  {
    "id": "422",
    "title": "The Boastful Turtle",
    "authors": "World Stories",
    "description": "A Filipino Story  *  Stories from folklore and fairytales are not always kind, but we view them through a small window where nothing can get in or out...",
    "vocabScore": 7183,
    "pageCount": 6,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/422.jpg"
  },
  {
    "id": "423",
    "title": "The Book Keeper",
    "authors": "World Stories",
    "description": "*  Santanu did not have much in this world. He owned a few items of clothing, a pair of cheap-looking trainers, a few pens and a book. An obsolete boo...",
    "vocabScore": 11367,
    "pageCount": 10,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/423.jpg"
  },
  {
    "id": "341",
    "title": "The Boy Who Cried Wolf",
    "authors": "World Stories",
    "description": "An Urdu Story  *  Once upon a time, there was a shepherd boy named Asif who lived in a village in one of the many beautiful valleys in Northern Pakist...",
    "vocabScore": 9738,
    "pageCount": 8,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/341.jpg"
  },
  {
    "id": "348",
    "title": "The Brothers Who Met Poverty",
    "authors": "World Stories",
    "description": "A Polish Story  *  Once upon a time, in a faraway village by a great river, there lived two brothers named Antek and Jonek.  Jonek was a kind-hearted...",
    "vocabScore": 14366,
    "pageCount": 13,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/348.jpg"
  },
  {
    "id": "424",
    "title": "The Bullies",
    "authors": "World Stories",
    "description": "A Pashto Story  *  There were once two boys who were very good friends. Their names were Arman, which means hope, and Batoor, which means brave. Arman...",
    "vocabScore": 5517,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/424.jpg"
  },
  {
    "id": "1122",
    "title": "The Bus to School",
    "authors": "World Stories",
    "description": "*  The thing which Joaquin liked the most about England was the bus. He and his mother caught the bus every day to go to Joaquin’s new school. He like...",
    "vocabScore": 6087,
    "pageCount": 5,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/1122.jpg"
  },
  {
    "id": "425",
    "title": "The Clever Crow",
    "authors": "World Stories",
    "description": "A Kannada Story  *  There once lived a crow called Bipu who lived in a small village called Siri. It was a very cold day and so Bipu was resting cosil...",
    "vocabScore": 2898,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/425.jpg"
  },
  {
    "id": "968",
    "title": "The Clever Old Woman",
    "authors": "World Stories",
    "description": "A Hindi story  *  Once upon a time, there lived an old woman in a kingdom ruled by a beautiful queen. The old woman had four sons who always fought wi...",
    "vocabScore": 5726,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/968.jpg"
  },
  {
    "id": "279",
    "title": "The Clever Rabbit",
    "authors": "World Stories",
    "description": "A Pashto Story  *  Once upon a time, deep in the jungle, there was a tiger who hunted for his dinner day and night.  The rest of the animals lived in...",
    "vocabScore": 5498,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/279.jpg"
  },
  {
    "id": "365",
    "title": "The Curse",
    "authors": "World Stories",
    "description": "A Portuguese Story  *  A very long time ago, there was a small village on the edge of the great forest. This was a peaceful village most of the time,...",
    "vocabScore": 7701,
    "pageCount": 6,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/365.jpg"
  },
  {
    "id": "323",
    "title": "The Curse of the Chameleon",
    "authors": "World Stories",
    "description": "A Kannada Story  *  Soon after the world began, God sat back and took a long look at the world. He was especially pleased with mankind. But, as time w...",
    "vocabScore": 4215,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/323.jpg"
  },
  {
    "id": "884",
    "title": "The Days of the Blackbird",
    "authors": "World Stories",
    "description": "An old tale from Northern Italy  *  Long ago, there was a family of blackbirds that lived quite happily. At the end of summer, they moved to a city ca...",
    "vocabScore": 3562,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/884.jpg"
  },
  {
    "id": "430",
    "title": "The Donkey",
    "authors": "World Stories",
    "description": "A Punjabi story  *  There was once a wealthy farmer who kept a stable of many donkeys. The farmer was very proud of his donkeys, and all day long they...",
    "vocabScore": 4334,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/430.jpg"
  },
  {
    "id": "426",
    "title": "The Donkey and the Qazi of Jaunpur",
    "authors": "World Stories",
    "description": "A Gujarati Story  *  There was once a boastful and proud teacher who lived in a small village in India. This man claimed that he was so intelligent th...",
    "vocabScore": 8115,
    "pageCount": 7,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/426.jpg"
  },
  {
    "id": "358",
    "title": "The Dragon of Kinabalu",
    "authors": "World Stories",
    "description": "A Chinese Story  *  Towards the end of the fourteenth century, China had begun to trade with many surrounding countries. Large fleets of ships set sai...",
    "vocabScore": 11574,
    "pageCount": 10,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/358.jpg"
  },
  {
    "id": "456",
    "title": "The Dream",
    "authors": "World Stories",
    "description": "*  There was once a boy called Jagan, whose dream was to become a famous cricket player. The boy would pray every day for his dream to come true, but...",
    "vocabScore": 5817,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/456.jpg"
  },
  {
    "id": "427",
    "title": "The Drop of Honey",
    "authors": "World Stories",
    "description": "A Farsi Story  *  Long, long ago this story was told. It has been told ever since, and here I tell it to you today ... the story of the drop of honey....",
    "vocabScore": 2784,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/427.jpg"
  },
  {
    "id": "330",
    "title": "The Eagle and the King",
    "authors": "World Stories",
    "description": "An Albanian Story  *  Once there was a boy who used to go hunting in the mountains with his bow and arrow. One day, the boy spent all afternoon huntin...",
    "vocabScore": 3726,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/330.jpg"
  },
  {
    "id": "431",
    "title": "The Elephant Who Lost his Patience",
    "authors": "World Stories",
    "description": "A Gujarati Story  *  Once upon a time, there was an ant and an elephant who lived in the jungle. The elephant was a patient and kind animal, but the a...",
    "vocabScore": 4103,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/431.jpg"
  },
  {
    "id": "250",
    "title": "The Emperor's New Clothes",
    "authors": "World Stories",
    "description": "A Danish Story  *  Once upon a time there was an Emperor who loved clothes! He loved clothes more than anything else!  Every year on his birthday he w...",
    "vocabScore": 5941,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/250.jpg"
  },
  {
    "id": "432",
    "title": "The Ever-So-Long Wool String",
    "authors": "World Stories",
    "description": "A Turkish Story  *  Once upon a time, there was an old woman who lived in a mountain village in Turkey. The old woman had three daughters. Their names...",
    "vocabScore": 5408,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/432.jpg"
  },
  {
    "id": "434",
    "title": "The Farmer and the Cow",
    "authors": "World Stories",
    "description": "A Chinese Story  *  Once upon a time, there was a farmer called Niu. Niu was not a rich farmer but he was very happy. He worked in the fields with his...",
    "vocabScore": 3345,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/434.jpg"
  },
  {
    "id": "269",
    "title": "The Fern Flower",
    "authors": "World Stories",
    "description": "A Polish Story  *  St John’s Night is the shortest night of the year. It is on this night that the legendary Fern Flower blooms somewhere in the fores...",
    "vocabScore": 12893,
    "pageCount": 11,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/269.jpg"
  },
  {
    "id": "265",
    "title": "The First Sunrise",
    "authors": "World Stories",
    "description": "An Aboriginal Tale from Australia  *  Long, long ago in the Dreamtime the Earth was dark. There was no light. It was very cold and very black. Huge gr...",
    "vocabScore": 3733,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/265.jpg"
  },
  {
    "id": "897",
    "title": "The Fisherman and the Bottle",
    "authors": "World Stories",
    "description": "*  A long time ago, in a land called Arabia, there lived an old fisherman.  Although he was old, he still went fishing every day. When he had fish to...",
    "vocabScore": 4008,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/897.jpg"
  },
  {
    "id": "435",
    "title": "The Fool and the Donkey",
    "authors": "World Stories",
    "description": "An Iranian Folktale  *  One morning, the fool woke up and he thought, ‘There is one thing I need, I need a donkey.’  So he left his home and walked un...",
    "vocabScore": 3057,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/435.jpg"
  },
  {
    "id": "376",
    "title": "The Fool, the Sheep and the End of the World",
    "authors": "World Stories",
    "description": "*  Nasreddin Hodja is the name of the wise fool in so many Turkish tales, and tales beyond Turkey through the Middle East and North Africa and far int...",
    "vocabScore": 2387,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/376.jpg"
  },
  {
    "id": "359",
    "title": "The Foolish Crocodile",
    "authors": "World Stories",
    "description": "A Gujarati Story  *  Once upon a time, there was a beautiful jamun tree that grew by the side of a river. A monkey lived in this tree; a happy and gen...",
    "vocabScore": 6830,
    "pageCount": 5,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/359.jpg"
  },
  {
    "id": "280",
    "title": "The Four Fox Cubs",
    "authors": "World Stories",
    "description": "A Punjabi Story  *  There was once a family of foxes who lived in the woods. There was a mother fox, a father fox and four baby fox cubs. The cubs wer...",
    "vocabScore": 5021,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/280.jpg"
  },
  {
    "id": "657",
    "title": "The Fox and the Stork",
    "authors": "World Stories",
    "description": "The fox and the stork lived in a wood.  One day, the fox invited the stork to come for a meal.  ‘Mrs Stork, come tomorrow at twelve o’clock,’ he said....",
    "vocabScore": 2359,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/657.jpg"
  },
  {
    "id": "267",
    "title": "The Frog Princess",
    "authors": "World Stories",
    "description": "*  Princess Ruby lived in a palace where her parents gave her everything she asked for.  Her favourite plaything was a golden ball. She loved the way...",
    "vocabScore": 5114,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/267.jpg"
  },
  {
    "id": "377",
    "title": "The Generous and Brave Warrior",
    "authors": "World Stories",
    "description": "A Spanish Story  *  Many years ago, long before you or I were born, the country of Spain was divided between two kings. The first king was ruler of th...",
    "vocabScore": 6152,
    "pageCount": 5,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/377.jpg"
  },
  {
    "id": "380",
    "title": "The Gingerbread Man",
    "authors": "World Stories",
    "description": "*  One day Mrs Brown the farmer’s wife thought, ‘Today I will make a gingerbread man.’  She mixed up all the ingredients then rolled a ball of gingerb...",
    "vocabScore": 6731,
    "pageCount": 5,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/380.jpg"
  },
  {
    "id": "628",
    "title": "The Ginseng Fairy",
    "authors": "World Stories",
    "description": "Long, long ago, there was a small village in Northern China where a greedy landowner lived. He had a poor servant called Little Hu, whose late parents...",
    "vocabScore": 4108,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/628.jpg"
  },
  {
    "id": "344",
    "title": "The Girl Who Loved Roses",
    "authors": "World Stories",
    "description": "A Moroccan Story  *  Many beautiful flowers grew in the park. There were lilies, carnations, violets, tulips and many more besides. The colours were a...",
    "vocabScore": 9691,
    "pageCount": 8,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/344.jpg"
  },
  {
    "id": "625",
    "title": "The Girl Who Wanted Three Husbands",
    "authors": "World Stories",
    "description": "*  Long ago on the mainland of Spain, there was once a merchant who had an intelligent and determined daughter. He found her three potential husbands...",
    "vocabScore": 4710,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/625.jpg"
  },
  {
    "id": "626",
    "title": "The Goddess Who Cast the Bell",
    "authors": "World Stories",
    "description": "In 1403, China was at the height of its power. At the top of the ladder was the great Emperor Kung-Lo, who had ruled for many years with plenty of suc...",
    "vocabScore": 12232,
    "pageCount": 11,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/626.jpg"
  },
  {
    "id": "891",
    "title": "The Golden Duck",
    "authors": "World Stories",
    "description": "A Polish story  *  Long ago, a young boy named Lutek lived in Warsaw. He was a shoemaker, and he worked in one of the factories in the Old Town. Lutek...",
    "vocabScore": 4953,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/891.jpg"
  },
  {
    "id": "977",
    "title": "The Golden Lira",
    "authors": "World Stories",
    "description": "A story from Turkey  *  There once lived a man who had a son. The son was spoiled by his mother until he grew up and became a young man. The boy had n...",
    "vocabScore": 3759,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/977.jpg"
  },
  {
    "id": "271",
    "title": "The Heathfield Hare",
    "authors": "World Stories",
    "description": "*  Once, there was a farmer’s wife. And one night she woke up and dreamt that it was day. And she took her basket on her arm and walked away from the...",
    "vocabScore": 3747,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/271.jpg"
  },
  {
    "id": "436",
    "title": "The Honest Girl",
    "authors": "World Stories",
    "description": "A Punjabi Story  *  A mother and a father had a daughter who grew from a baby into a beautiful girl. The mother and father were very proud of their da...",
    "vocabScore": 5365,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/436.jpg"
  },
  {
    "id": "437",
    "title": "The Innocent Punishment",
    "authors": "World Stories",
    "description": "A Hindi Story  *  This is a story about Akbar, the Emperor of India, and his loyal and witty advisor Birbal.  It was a fine morning in the palace. The...",
    "vocabScore": 3655,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/437.jpg"
  },
  {
    "id": "382",
    "title": "The Island of the Sun",
    "authors": "World Stories",
    "description": "A Chinese Story  *  There was once a farmer who had two sons.  The older son was selfish and greedy, while the younger son was kind and generous.  Whe...",
    "vocabScore": 4497,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/382.jpg"
  },
  {
    "id": "661",
    "title": "The Kind Goats",
    "authors": "World Stories",
    "description": "In a small village there was a river with a narrow bridge.  The bridge was so narrow that two people could not cross over it at the same time.  One da...",
    "vocabScore": 2058,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/661.jpg"
  },
  {
    "id": "383",
    "title": "The King with Donkey Ears",
    "authors": "World Stories",
    "description": "A Somali Story  *  A long time ago, there was a king who had floppy ears shaped just like the ears of a donkey. The king was very embarrassed about hi...",
    "vocabScore": 4661,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/383.jpg"
  },
  {
    "id": "274",
    "title": "The Lady Who Lives on the Moon",
    "authors": "World Stories",
    "description": "A Chinese Story  *  Once upon a time, there was a beautiful warrior called Chang’e who was married to a brave and strong archer named Houyi. The coupl...",
    "vocabScore": 4859,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/274.jpg"
  },
  {
    "id": "324",
    "title": "The Legend of Mafumeira",
    "authors": "World Stories",
    "description": "A Portuguese Story from Brazil  *  Deep within the forest there lives the tallest of all trees. They stretch their thick branches full of leaves up in...",
    "vocabScore": 8344,
    "pageCount": 7,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/324.jpg"
  },
  {
    "id": "384",
    "title": "The Lion and the Beetle",
    "authors": "World Stories",
    "description": "A story from South Africa  *  Lion was very proud and very vain. He called himself the king of all the animals and he loved to stomp around the savann...",
    "vocabScore": 3844,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/384.jpg"
  },
  {
    "id": "247",
    "title": "The Lion and the Jackal",
    "authors": "World Stories",
    "description": "A Zulu Story  *  One day long ago, Jackal was trotting through a narrow, rocky pass in the mountain. He was sniffing the ground trying to find somethi...",
    "vocabScore": 2458,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/247.jpg"
  },
  {
    "id": "439",
    "title": "The Lion and the Sheep",
    "authors": "World Stories",
    "description": "A Farsi Story  *  Once upon a time, there lived a lion who was always bragging about his bravery, his strength, and his cunning. ‘There is no animal i...",
    "vocabScore": 4217,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/439.jpg"
  },
  {
    "id": "440",
    "title": "The Lion with the Red Eyes",
    "authors": "World Stories",
    "description": "A Somali Story  *  A very long time ago, there was a small village in Somalia in Eastern Africa. On the edge of the village there was rich farmland wh...",
    "vocabScore": 6891,
    "pageCount": 5,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/440.jpg"
  },
  {
    "id": "995",
    "title": "The Little Shepherd Boy",
    "authors": "World Stories",
    "description": "*  Peter was a young shepherd boy. He looked after lambs and sheep.  He stayed on the hillside with his flock every day, from morning until evening. I...",
    "vocabScore": 2298,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/995.jpg"
  },
  {
    "id": "441",
    "title": "The Lost Camel",
    "authors": "World Stories",
    "description": "An Indian Folktale  *  Once, there was a merchant, not a rich merchant. And he had a camel, not a beautiful camel. But he loved that camel. And one da...",
    "vocabScore": 4021,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/441.jpg"
  },
  {
    "id": "336",
    "title": "The Love of the Forest",
    "authors": "World Stories",
    "description": "A Brazilian Story  *  The sun rises above the Amazon rainforest and the huge, evergreen trees allow rays of light to pass between their leaves and pai...",
    "vocabScore": 11723,
    "pageCount": 10,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/336.jpg"
  },
  {
    "id": "386",
    "title": "The Lucky Man",
    "authors": "World Stories",
    "description": "A Spanish Story  *  There was once a very talented craftsman who was hired to build a small church in a small village. The man was given a month to co...",
    "vocabScore": 6395,
    "pageCount": 5,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/386.jpg"
  },
  {
    "id": "351",
    "title": "The Magic Mirror",
    "authors": "World Stories",
    "description": "A Spanish Story  *  The King of Granada decided to marry. First, the news was told to his barber, then to the night watchman, and then to the oldest w...",
    "vocabScore": 5438,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/351.jpg"
  },
  {
    "id": "251",
    "title": "The Magic Paintbrush",
    "authors": "World Stories",
    "description": "A Chinese Folktale  *  Once upon a time, there was a young man called Ma Liang. He was poor and kind and liked drawing so much that he drew pictures e...",
    "vocabScore": 3399,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/251.jpg"
  },
  {
    "id": "658",
    "title": "The Magic Porridge Pot",
    "authors": "World Stories",
    "description": "A poor girl lived with her mother in a town. They were hungry, but they had nothing to eat.  The girl said, ‘I’ll go into the wood to look for mushroo...",
    "vocabScore": 2179,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/658.jpg"
  },
  {
    "id": "442",
    "title": "The Monkey",
    "authors": "World Stories",
    "description": "A Punjabi Story  *  Once upon a time, there was a naughty monkey who lived on the rooftops of a little town.  One day, the monkey spied a man in the s...",
    "vocabScore": 4900,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/442.jpg"
  },
  {
    "id": "659",
    "title": "The Monkey King and the Ghost",
    "authors": "World Stories",
    "description": "The  and the  In a dense jungle lived a gang of monkeys. The king of the monkeys was very wise. One day he called his gang together.  ‘My beloved monk...",
    "vocabScore": 2530,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/659.jpg"
  },
  {
    "id": "993",
    "title": "The Monkey and the Crocodile",
    "authors": "World Stories",
    "description": "*  Once upon a time, a monkey lived in a tree by a river. The monkey was alone as he had no friends or family but he was happy and content. The tree g...",
    "vocabScore": 4749,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/993.jpg"
  },
  {
    "id": "361",
    "title": "The Mouse",
    "authors": "World Stories",
    "description": "A Polish Story  *  This is the story of a little girl who was not scared of anything … well, at least until she grew a bit older.  The little girl liv...",
    "vocabScore": 10818,
    "pageCount": 9,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/361.jpg"
  },
  {
    "id": "444",
    "title": "The Mystery of the Buried Treasure",
    "authors": "World Stories",
    "description": "An Urdu Story  *  Once upon a time, a farmer and his four sons lived in a village in a part of Pakistan called the Punjab, where many farms were to be...",
    "vocabScore": 7502,
    "pageCount": 6,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/444.jpg"
  },
  {
    "id": "660",
    "title": "The Phoenix Bird",
    "authors": "World Stories",
    "description": "At the beginning of time, there was a beautiful garden called Paradise. Adam and Eve lived in that garden and life was wonderful and good. The garden...",
    "vocabScore": 4103,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/660.jpg"
  },
  {
    "id": "975",
    "title": "The Pied Piper of Hamelin",
    "authors": "World Stories",
    "description": "*  Hamelin was a beautiful town in Germany. The people who lived there were happy.  Then, one day, rats came to Hamelin in their hundreds!  There were...",
    "vocabScore": 2651,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/975.jpg"
  },
  {
    "id": "388",
    "title": "The Pompous Peacock",
    "authors": "World Stories",
    "description": "A Hindi Story  *  In the beginning of time, there was only one of each kind of animal so every one was different.  In the Sunderbans National Park in...",
    "vocabScore": 4362,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/388.jpg"
  },
  {
    "id": "892",
    "title": "The Poor Man and the Magical Cat",
    "authors": "World Stories",
    "description": "A story from Brazil  *  Once upon a time, there was a very poor young man. He lived in a tiny hut with his cat.  His cat was extraordinary. It could t...",
    "vocabScore": 5371,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/892.jpg"
  },
  {
    "id": "326",
    "title": "The Prince and the Honest Girl",
    "authors": "World Stories",
    "description": "A Story from Saudi Arabia  *  A long time ago, there was a young Prince who wanted very much to find a wife. The Prince wanted his wife to be beautifu...",
    "vocabScore": 3713,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/326.jpg"
  },
  {
    "id": "327",
    "title": "The Princess and the Golden Ball",
    "authors": "World Stories",
    "description": "An Iraqi Story  *  Once there was a beautiful princess who lived with her father in a huge palace. Although the princess was very beautiful, she was a...",
    "vocabScore": 9133,
    "pageCount": 8,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/327.jpg"
  },
  {
    "id": "272",
    "title": "The Princess and the Pea",
    "authors": "World Stories",
    "description": "A Dutch Story  *  Once upon a time, there was a prince who was very, very, very fussy.  He decided that the time had come for him to get married, but...",
    "vocabScore": 4288,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/272.jpg"
  },
  {
    "id": "342",
    "title": "The Princess of Riddles",
    "authors": "World Stories",
    "description": "A Portuguese Story  *  There once was a beautiful princess called Maria who could solve any riddle. Maria was a striking girl who was clearly very bea...",
    "vocabScore": 14253,
    "pageCount": 13,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/342.jpg"
  },
  {
    "id": "445",
    "title": "The Princess' Wedding",
    "authors": "World Stories",
    "description": "An Akan Story  *  There was joy in the air as the villagers of the Asante tribe in Kumasi gathered for the three-day celebration of the Crown Princess...",
    "vocabScore": 9856,
    "pageCount": 8,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/445.jpg"
  },
  {
    "id": "446",
    "title": "The Rabbit and the Jaguar",
    "authors": "World Stories",
    "description": "A Mexican Folktale  *  There lived once, an old man and an old woman. And all they had in the world was one rabbit and one jaguar.  They kept the rabb...",
    "vocabScore": 3646,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/446.jpg"
  },
  {
    "id": "253",
    "title": "The Rainbow Serpent",
    "authors": "World Stories",
    "description": "An Aboriginal Story from Australia  *  Long ago in the Dreamtime a group of Aboriginals were out hunting. After many hours, they grew tired and decide...",
    "vocabScore": 3145,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/253.jpg"
  },
  {
    "id": "357",
    "title": "The Singing Drum",
    "authors": "World Stories",
    "description": "A Nigerian Story  *  Once upon a time, there was a boy called Atilola. His parents loved him dearly because he was their only child and they made sure...",
    "vocabScore": 10472,
    "pageCount": 9,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/357.jpg"
  },
  {
    "id": "970",
    "title": "The Sleeping King",
    "authors": "World Stories",
    "description": "A traditional Spanish tale  *  Once upon a time, there was a beautiful princess who was bored with life at court.  As she was the king’s daughter, she...",
    "vocabScore": 7423,
    "pageCount": 6,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/970.jpg"
  },
  {
    "id": "972",
    "title": "The Sly Fox and her Tricks",
    "authors": "World Stories",
    "description": "Once upon a time, there was a fox, as sly as foxes are. She’d been prowling for food all night and couldn’t find any. When dawn broke, the fox crawled...",
    "vocabScore": 5271,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/972.jpg"
  },
  {
    "id": "369",
    "title": "The Song of the Armadillo",
    "authors": "World Stories",
    "description": "A Bolivian Folktale  *  Once there was an armadillo who lived in the Bolivian rainforest. He loved music more than anything in the world and all he wa...",
    "vocabScore": 5317,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/369.jpg"
  },
  {
    "id": "328",
    "title": "The Spider and his Two Friends",
    "authors": "World Stories",
    "description": "A Nigerian Story  *  Alantakun the spider had two friends. One lived in the village on the right. The other lived in the village on the left.  One day...",
    "vocabScore": 3687,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/328.jpg"
  },
  {
    "id": "389",
    "title": "The Story of Layla and Majnun",
    "authors": "World Stories",
    "description": "An Afghan Story  *  Qays ibn al-Mulawwah was just a boy when he fell deeply in love with Layla Al-Aamiriya. He was sure of this love on the very first...",
    "vocabScore": 4847,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/389.jpg"
  },
  {
    "id": "883",
    "title": "The Story of Narcissus",
    "authors": "World Stories",
    "description": "A tale from the traditional myths and legendsof Ancient Greece  *  A very very long time ago, the people of Ancient Greece believed many gods and godd...",
    "vocabScore": 3555,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/883.jpg"
  },
  {
    "id": "448",
    "title": "The Story of Niu Lang and Zhi Nu",
    "authors": "World Stories",
    "description": "A Chinese Story  *  This legend has existed for nearly two millennia.  Niu Lang wasn’t always a simple cow herder and Zhi Nu wasn’t always a cloud-wea...",
    "vocabScore": 6690,
    "pageCount": 5,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/448.jpg"
  },
  {
    "id": "449",
    "title": "The Story of the Dragon Boat Festival",
    "authors": "World Stories",
    "description": "A Chinese Story  *  A very long time ago, during a period known as the Zhou Dynasty, China was divided into seven warring kingdoms. This was a time of...",
    "vocabScore": 3105,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/449.jpg"
  },
  {
    "id": "450",
    "title": "The Tale of Half-a-Chick",
    "authors": "World Stories",
    "description": "A Spanish Story  *  On the rolling fields of La Campiña, very close to beautiful Seville, there once lived a plump red hen who made her home on a larg...",
    "vocabScore": 9581,
    "pageCount": 8,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/450.jpg"
  },
  {
    "id": "965",
    "title": "The Tale of the Wawel Dragon",
    "authors": "World Stories",
    "description": "A Polish story  *  Hundreds of years ago, beneath the royal castle of Wawel, there lay a cruel and menacing three-headed dragon named Smok Wawelski. H...",
    "vocabScore": 6664,
    "pageCount": 5,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/965.jpg"
  },
  {
    "id": "254",
    "title": "The Three Billy-Goats Gruff",
    "authors": "World Stories",
    "description": "A Norwegian Story  *  Once upon a time there were three Billy-Goats Gruff; Little Billy-Goat, Middle-Sized Billy Goat and Great Big Billy-Goat, who li...",
    "vocabScore": 4356,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/254.jpg"
  },
  {
    "id": "457",
    "title": "The Three Brothers",
    "authors": "World Stories",
    "description": "An Albanian Story  *  There was once a poor man who died and left his wife and son alone. The boy was named Kordha, and as time passed he grew to be b...",
    "vocabScore": 7767,
    "pageCount": 6,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/457.jpg"
  },
  {
    "id": "894",
    "title": "The Three Butterflies",
    "authors": "World Stories",
    "description": "An Italian story  *  Once upon a time, there were three beautiful butterflies. The three were different colours. One was red, one was yellow, and one...",
    "vocabScore": 2151,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/894.jpg"
  },
  {
    "id": "390",
    "title": "The Three Diamonds",
    "authors": "World Stories",
    "description": "A Tamil Folktale  *  There was a young thief and he lived with his grandmother.  ‘Oh, my grandson, will you not change your ways? I will die an unhapp...",
    "vocabScore": 6711,
    "pageCount": 5,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/390.jpg"
  },
  {
    "id": "459",
    "title": "The Three Dolls",
    "authors": "World Stories",
    "description": "An Iranian Folktale  *  The Sultan of Persia was a clever man – well read – and there was nothing he loved more than solving problems, puzzles, riddle...",
    "vocabScore": 4454,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/459.jpg"
  },
  {
    "id": "656",
    "title": "The Three Fish",
    "authors": "World Stories",
    "description": "Once, three fish lived in a pond. One evening, some fishermen passed by the pond and saw the fish.  ‘This pond is full of fish’, they told each other....",
    "vocabScore": 2317,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/656.jpg"
  },
  {
    "id": "262",
    "title": "The Three Little Pigs",
    "authors": "World Stories",
    "description": "Mrs Pig was very tired: 'Oh dear,' she said to her three little pigs, 'I can’t do this work anymore, I’m afraid you must leave home and make your own...",
    "vocabScore": 5822,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/262.jpg"
  },
  {
    "id": "367",
    "title": "The Three Oranges",
    "authors": "World Stories",
    "description": "A French Story  *  Once upon a time, there was a prince who never laughed nor smiled. Amongst his people he had the reputation of being a sombre young...",
    "vocabScore": 10345,
    "pageCount": 9,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/367.jpg"
  },
  {
    "id": "391",
    "title": "The Tortoise and the Hare",
    "authors": "World Stories",
    "description": "*  Once upon a time, in a field not too far from you, there was an energetic and happy hare and a sleepy tortoise.  The happy hare was called Noel and...",
    "vocabScore": 4496,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/391.jpg"
  },
  {
    "id": "460",
    "title": "The Tortoise and the Three Brothers",
    "authors": "World Stories",
    "description": "A Nigerian Story  *  Once upon a time, there were three orphans, whose names were Otarun, Akope and Awekun. The brothers had reached such an age that...",
    "vocabScore": 12089,
    "pageCount": 11,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/460.jpg"
  },
  {
    "id": "461",
    "title": "The Two Old Women: Tetan Buri and Boka Buri",
    "authors": "World Stories",
    "description": "A Bengali Folktale  *  Tetan Buri ... aha! Boka Buri ... hmmm.  Tetan Buri ... aha! Boka Buri ... hmmm.  Tetan Buri ... aha! Boka Buri ... hmmm.  Ther...",
    "vocabScore": 4888,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/461.jpg"
  },
  {
    "id": "464",
    "title": "The Washerman's Donkey",
    "authors": "World Stories",
    "description": "An Urdu Story  *  Once upon a time, there was a little boy called Haroon.  Haroon lived with his parents in a small village just outside Karachi, whic...",
    "vocabScore": 5406,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/464.jpg"
  },
  {
    "id": "623",
    "title": "The Well",
    "authors": "World Stories",
    "description": "A long time ago, there were four families who lived in a small village in Somalia. The first family would argue all of the time, the second family wer...",
    "vocabScore": 5695,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/623.jpg"
  },
  {
    "id": "360",
    "title": "The Wind and the Sun",
    "authors": "World Stories",
    "description": "An Akan Story  *  One day, a boastful wind declared to the sun, ‘You know that I am the strongest and most effective of all weather!’  And the sun rep...",
    "vocabScore": 3936,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/360.jpg"
  },
  {
    "id": "363",
    "title": "The Wounded Lion",
    "authors": "World Stories",
    "description": "A Spanish Story  *  Once upon a time, there was a very poor girl whose job it was to herd the cows from the village to the field, where they would eat...",
    "vocabScore": 7394,
    "pageCount": 6,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/363.jpg"
  },
  {
    "id": "466",
    "title": "To Give",
    "authors": "World Stories",
    "description": "A Hindi Story  *  Once upon a time, there was a very powerful and very generous King who gave much of his gold to the poor people of his lands. Each m...",
    "vocabScore": 4848,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/466.jpg"
  },
  {
    "id": "467",
    "title": "Turtle and Monkey",
    "authors": "World Stories",
    "description": "A Filipino Folktale  *  Monkey stood at the edge of the river and watched Turtle swimming against the torrent with a tree that he had caught in the fl...",
    "vocabScore": 4515,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/467.jpg"
  },
  {
    "id": "1048",
    "title": "What We Plant, We Will Eat",
    "authors": "World Stories",
    "description": "*  A long time ago, two brothers lived with their father in a small house in Korea.  The younger brother worked hard and was kind to everyone but the...",
    "vocabScore": 5977,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#4f46e5",
    "coverUrl": "http://localhost:8080/world-stories/covers/1048.jpg"
  },
  {
    "id": "468",
    "title": "Who is the Cleverest, Sheep or Lion?",
    "authors": "World Stories",
    "description": "A Somali Story  *  A very long time ago, there was a crafty lion and a clever sheep. One day, the clever sheep was eating some grass in a clearing wit...",
    "vocabScore": 4862,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#6c8c36",
    "coverUrl": "http://localhost:8080/world-stories/covers/468.jpg"
  },
  {
    "id": "255",
    "title": "Why Anansi has Eight Skinny Legs",
    "authors": "World Stories",
    "description": "An Akan Story  *  Once upon a time, there lived a spider called Anansi. Though Anansi’s wife was a very good cook, the greedy spider loved nothing mor...",
    "vocabScore": 5213,
    "pageCount": 4,
    "isSimplified": false,
    "coverColor": "#e6e0d4",
    "coverUrl": "http://localhost:8080/world-stories/covers/255.jpg"
  },
  {
    "id": "266",
    "title": "Why Elephants Can't Fly",
    "authors": "World Stories",
    "description": "A Hindi Story  *  A long time ago, much longer than most people can remember, elephants could fly! They had four enormous wings and they whizzed throu...",
    "vocabScore": 6233,
    "pageCount": 5,
    "isSimplified": false,
    "coverColor": "#dc2626",
    "coverUrl": "http://localhost:8080/world-stories/covers/266.jpg"
  },
  {
    "id": "880",
    "title": "Why the Cheetah's Cheeks Are Stained",
    "authors": "World Stories",
    "description": "A Zulu Story  *  Long ago, a wicked and lazy hunter was sitting under a tree. He was thinking that it was too hot to be bothered with the arduous task...",
    "vocabScore": 4055,
    "pageCount": 3,
    "isSimplified": false,
    "coverColor": "#d97706",
    "coverUrl": "http://localhost:8080/world-stories/covers/880.jpg"
  },
  {
    "id": "469",
    "title": "Why the Sky is so High",
    "authors": "World Stories",
    "description": "A Bengali Story  *  Many years ago, the sky was so low that if you reached up you could touch it with your fingers.  And in northern India where the s...",
    "vocabScore": 3482,
    "pageCount": 2,
    "isSimplified": false,
    "coverColor": "#2563eb",
    "coverUrl": "http://localhost:8080/world-stories/covers/469.jpg"
  },
  {
    "id": "470",
    "title": "Why the Sun and Moon Live in the Sky",
    "authors": "World Stories",
    "description": "A Nigerian Story  *  Many years ago, the sun and water were great friends, and they both lived on the earth together. The sun often used to visit the...",
    "vocabScore": 2910,
    "pageCount": 1,
    "isSimplified": false,
    "coverColor": "#9333ea",
    "coverUrl": "http://localhost:8080/world-stories/covers/470.jpg"
  }
];